# -*- coding: utf-8 -*-
"""handling Mixed Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFIrNk_e5mFwGxC6MLi5Rk-vWq1YUtNZ

MIxed Data means categorical and numerical data mixed. Like B5 C32. So we have to split them into 2 columns. 1 will store B C all cat. values and 2nd will store numerical values.
"""

import numpy as np
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day33-handling-mixed-variables/titanic.csv")

df.head()

df.shape

#extract numerical part...look at number column it has mixed data
df['number_numerical'] = pd.to_numeric(df['number'],errors="coerce",downcast='integer')

#extract categorical part
df['number_categorical'] = np.where(df['number_numerical'].isnull(),df['number'],np.nan)

df.head()

"""Now look at Cabin and Ticket column which has mixed data"""

df['cabin_num'] = df['Cabin'].str.extract('(\d+)') #captures numeric part
df['cabin_cat'] = df['Cabin'].str[0] # captures categorical part

df.head()